# Generated by Django 3.0.6 on 2020-05-24 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='emp_image2',
            field=models.ImageField(default='null', upload_to='style/'),
            preserve_default=False,
        ),
    ]
