# Generated by Django 3.0.6 on 2020-05-24 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0002_employee_emp_image2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='name',
        ),
    ]
